Repository opt-nc/domaine-nc-javafx, pull requests merged in 2023-05, with the labels that each got.

#19 Update README.md
  README.md
Labels: documentation, quickfix

#27 :memo: AMélioration UX workflow
  .github/workflows/mavenCI.yaml
Labels: documentation, enhancement, quickfix

#25 :penguin: :rotating_light: renommer la clé x-rapidapi-key en x_rapidapi_key :rotating_light:
  .env.template
  README.md
  src/main/java/com/unc/domainenc/DomaineNcApp.java
Labels: bug, enhancement

#30 :link: Liens ridet et domaine
  src/main/java/com/unc/domainenc/DomaineNcController.java
  src/main/java/com/unc/domainenc/DomaineNcInfoController.java
  src/main/resources/com/unc/domainenc/InterfaceDomaineNc.fxml
Labels: enhancement
