Repository opt-nc/domaine-nc-javafx, pull requests merged in 2023-06, with the labels that each got.

#40 Icon souris changement
  src/main/java/com/unc/domainenc/DomaineNcController.java
  src/main/java/com/unc/domainenc/DomaineNcInfoController.java
Labels: enhancement, quickfix

#41 23 calendar déterminer dateheure et durée de la soutenance unc
  docs/RAPPORT.pdf
  docs/README.md
  docs/SOUTENANCE.pdf
  docs/SOUTENANCE.pptx
Labels: documentation, quickfix

#49 repo migration
  README.md
Labels: documentation, RUN
